version: '3.8'

services:
  webhook-handler:
    image: aash591/ztnet-webhook-telegram-bot:latest  # Your Docker Hub image
    container_name: webhook-handler
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "Your actual bot token"  # Your actual bot token
      TELEGRAM_CHAT_IDS: "CHAT_ID_1,CHAT_ID_2"  # Your chat ID
      WEBHOOK_URL: "http://webhook-handler:5000/webhook"  # Update if needed
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge
